# Podfile for ONNX Runtime Mobile + Core ML Demo
platform :ios, '16.0'
use_frameworks!

# Specify the Xcode project location
project 'ORTCoreMLDemo/ORTCoreMLDemo.xcodeproj'

target 'ORTCoreMLDemo' do
  # Use Objective-C wrapper - much easier than C API
  pod 'onnxruntime-objc'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
    end
  end
end

